source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bootsnap"
gem "listen"
gem "pg", "< 1.0"
gem "que", ENV.fetch("QUE_VERSION")
gem "que-scheduler", path: "../../../../"
gem "rails", ENV.fetch("RAILS_VERSION")
