# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fasterer/all/fasterer.rbi
#
# fasterer-0.8.3

module Fasterer
end
class Fasterer::MethodDefinition
  def arguments; end
  def arguments_element; end
  def block_argument_name; end
  def body; end
  def element; end
  def has_block?; end
  def initialize(element); end
  def last_argument_element; end
  def method_name; end
  def name; end
  def set_arguments; end
  def set_block_argument_name; end
  def set_body; end
  def set_method_name; end
  def setter?; end
end
class Fasterer::MethodDefinitionArgument
  def default_argument?; end
  def element; end
  def initialize(element); end
  def keyword_argument?; end
  def name; end
  def regular_argument?; end
  def set_argument_type; end
  def set_name; end
  def type; end
end
class Fasterer::MethodCall
  def arguments; end
  def arguments_element; end
  def block_argument_names; end
  def block_body; end
  def call_element; end
  def element; end
  def has_block?; end
  def initialize(element); end
  def lambda_literal?; end
  def method_name; end
  def name; end
  def receiver; end
  def receiver_element; end
  def set_arguments; end
  def set_block_argument_names; end
  def set_block_body; end
  def set_block_presence; end
  def set_call_element; end
  def set_method_name; end
  def set_receiver; end
end
class Fasterer::ReceiverFactory
  def self.new(receiver_info); end
end
class Fasterer::VariableReference
  def initialize(reference_info); end
  def name; end
end
class Fasterer::Argument
  def element; end
  def initialize(element); end
  def type; end
  def value; end
end
class Fasterer::Primitive
  def array?; end
  def element; end
  def initialize(element); end
  def range?; end
  def type; end
end
class Fasterer::RescueCall
  def element; end
  def initialize(element); end
  def rescue_classes; end
  def set_rescue_classes; end
end
class Fasterer::OffenseCollector
  def [](offense_name); end
  def any?(*args, &block); end
  def count(*args, &block); end
  def each(*args, &block); end
  def group_by(*args, &block); end
  def initialize; end
  def push(*args, &block); end
  extend Forwardable
end
class Fasterer::Parser
  def self.parse(ruby_code); end
end
class Fasterer::Offense
  def explanation; end
  def initialize(offense_name, line_number); end
  def line; end
  def line_number; end
  def name; end
  def offense_name; end
end
module Fasterer::Offensive
  def add_offense(offense_name, element_line_number = nil); end
  def check_offense; end
  def offense; end
  def offense=(arg0); end
  def offense_detected?; end
  def offensive?; end
end
class Fasterer::MethodCallScanner
  def check_each_offense; end
  def check_each_with_index_offense; end
  def check_fetch_offense; end
  def check_first_offense; end
  def check_flatten_offense; end
  def check_gsub_offense; end
  def check_last_offense; end
  def check_merge_bang_offense; end
  def check_module_eval_offense; end
  def check_offense; end
  def check_range_include_offense; end
  def check_sort_offense; end
  def check_symbol_to_proc; end
  def element; end
  def initialize(element); end
  def method_call; end
  include Fasterer::Offensive
end
class Fasterer::RescueCallScanner
  def check_offense; end
  def element; end
  def initialize(element); end
  def rescue_call; end
  include Fasterer::Offensive
end
class Fasterer::MethodDefinitionScanner
  def check_offense; end
  def element; end
  def initialize(element); end
  def method_definition; end
  def scan_block_call_offense; end
  def scan_getter_and_setter_offense; end
  def scan_getter_offense; end
  def scan_setter_offense; end
  def traverse_tree(sexp_tree, &block); end
  include Fasterer::Offensive
end
class Fasterer::Analyzer
  def errors; end
  def file_path; end
  def initialize(file_path); end
  def path; end
  def scan; end
  def scan_by_token(token, element); end
  def scan_for_loop(element); end
  def scan_method_calls(element); end
  def scan_method_definitions(element); end
  def scan_rescue(element); end
  def traverse_sexp_tree(sexp_tree); end
end
