# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sorbet-struct-comparable/all/sorbet-struct-comparable.rbi
#
# sorbet-struct-comparable-1.0.0

module SorbetStructComparable
end
module T
end
class T::Struct < T::InexactStruct
end
module T::Struct::ActsAsComparable
  def <=>(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Comparable
end
