# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/zonebie/all/zonebie.rbi
#
# zonebie-0.6.1

module Zonebie
  def self.add_backend(backend); end
  def self.backend; end
  def self.backend=(backend); end
  def self.quiet; end
  def self.quiet=(arg0); end
  def self.random_timezone; end
  def self.set_random_timezone; end
end
module Zonebie::Backends
end
class Zonebie::Backends::ActiveSupport
  def self.name; end
  def self.usable?; end
  def self.zone=(zone); end
  def self.zones; end
end
class Zonebie::Backends::TZInfo
  def self.name; end
  def self.usable?; end
  def self.zone=(zone); end
  def self.zones; end
end
module RuboCop
end
module RuboCop::Cop
end
module RuboCop::Cop::Style
end
class RuboCop::Cop::Style::RedundantConditional < RuboCop::Cop::Cop
  include RuboCop::Cop::Alignment
end
