version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 0 1 3,9 *"
  groups:
    everything:
      patterns:
      - "*" # Bundle update everything
