# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `tapioca todo`.

# typed: false

module ::ActiveJob::Base; end
module ::Fugit::Cron; end
module ::Hashie::Dash; end
module ::Hashie::Extensions::Dash::PropertyTranslation; end
module Que::DEFAULT_QUEUE; end
module Que::Job; end
