# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::ActiveJob::Base; end
module ::ActiveJob::ConfiguredJob; end
module ::ActiveJob::QueueAdapters::QueAdapter::JobWrapper; end
module Que::DEFAULT_QUEUE; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
