name: Publish gem to rubygems.org

on:
  push:
    branches: [master]
    paths:
    - 'lib/que/scheduler/version.rb'

permissions:
  contents: read

jobs:
  push:
    if: github.repository == 'hlascelles/que-scheduler'
    runs-on: ubuntu-latest

    environment:
      name: rubygems.org
      url: https://rubygems.org/gems/que-scheduler

    permissions:
      contents: write
      id-token: write

    steps:
    # Set up
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true
        ruby-version: ruby

    # Release
    - name: Publish to RubyGems
      uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1.1.1

    - name: Create GitHub release
      run: |
        tag_name="$(git describe --tags --abbrev=0)"
        gh release create "${tag_name}" --verify-tag --draft --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
